/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#630ed4",
        "primary-container": "#7c3aed",
        "on-primary": "#ffffff",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d2bbff",
        "on-primary-fixed": "#25005a",
        "secondary": "#944a00",
        "secondary-container": "#fd933d",
        "secondary-fixed": "#ffdcc5",
        "secondary-fixed-dim": "#ffb783",
        "on-secondary-fixed": "#301400",
        "on-secondary-container": "#693300",
        "tertiary": "#005b3d",
        "tertiary-container": "#007650",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#d0dbed",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "on-surface": "#121c2a",
        "on-surface-variant": "#4a4455",
        "outline": "#7b7487",
        "outline-variant": "#ccc3d8",
        "error": "#ba1a1a",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        margin: "1.5rem",
      },
    },
  },
  plugins: [],
};
