export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#121c2a",
        "tertiary-container": "#007650",
        "secondary-fixed-dim": "#ffb783",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#27313f",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed": "#ffdcc5",
        "surface-container-low": "#eff4ff",
        "primary": "#630ed4",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#301400",
        "outline-variant": "#ccc3d8",
        "tertiary": "#005b3d",
        "error": "#ba1a1a",
        "outline": "#7b7487",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fc",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#d2bbff",
        "on-secondary-container": "#693300",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed": "#eaddff",
        "on-surface-variant": "#4a4455",
        "on-background": "#121c2a",
        "on-secondary-fixed-variant": "#713700",
        "surface-dim": "#d0dbed",
        "surface": "#f8f9ff",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-container": "#fd933d",
        "on-primary-fixed": "#25005a",
        "on-tertiary-fixed": "#002113",
        "surface-bright": "#f8f9ff",
        "secondary": "#944a00",
        "inverse-primary": "#d2bbff",
        "surface-variant": "#d9e3f6",
        "surface-container-highest": "#d9e3f6",
        "on-primary": "#ffffff",
        "on-primary-container": "#ede0ff",
        "primary-container": "#7c3aed",
        "on-primary-fixed-variant": "#5a00c6",
        "on-error": "#ffffff",
        "surface-tint": "#732ee4",
        "background": "#f8f9ff",
        "on-tertiary-container": "#76ffc2",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "0.75rem",
        "gutter": "1.25rem",
        "margin": "2.5rem",
      },
      fontFamily: {
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "display-hero": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "display-hero-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "display-hero": ["52px", { lineHeight: "60px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-lg": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
